### ISSUE TITLE
services.AddLiteBus throws System.TypeLoadException

### ISSUE THREAD

**Issue by TorreyGarland** [litenova/LiteBus#12]
```
Exception Unhandled:
System.TypeLoadException: 'Could not load type 'LiteBus.Messaging.Abstractions.IPostHandlerHook" from assembly 'LiteBus.Messaging.Abstractions, Version=0.8.1.0, Culture=neutral, PublicKeyToken=null'.'
```
I have an MVC Core web app, .NET 5.0.

Inside of ConfigureServices, I make a call to services.AddLiteBus((builder) => builder.Register(typeof(MyDbContext).Assembly) which is in a separate project references by the web app.

I am following the instructions from the readme for Litebus for handler registration.

Both LiteBus and LiteBus.Extensions.MicrosoftDependencyInjection package have been imported into both projects.

**Comment by TorreyGarland** [comment]
Please disregard.  It works after updating to the latest nuget package.

Please update the readme.md documentation.  There is no "Register" extension method, but "RegisterFrom" works.

**Comment by litenova** [comment]
Sorry, my bad
I'll update it asap
