### ISSUE TITLE
Question about Cancellation Tokens parameters

### ISSUE THREAD

**Issue by TorreyGarland** [litenova/LiteBus#5]
Is there a particular reason that System.Threading.CancellationToken is not included in the various command handler interface method definitions as a parameter?

**Comment by litenova** [comment]
Not really,
Since I created this project to meet my own needs, I did not need the cancellation tokens. However, I understand your concern and I will add the cancellation tokens by tomorrow.

**Comment by litenova** [comment]
#6

**Comment by TorreyGarland** [comment]
Thanks!!!

**Comment by TorreyGarland** [comment]
By the way, good job with this package!
