### ISSUE TITLE
StreamAsync always returns null result

### ISSUE THREAD

**Issue by TorreyGarland** [litenova/LiteBus#7]
Even with hard-coded values within the implementation, a call to QueryMediator.StreamAsync always returns a null instance of IAsyncEnumerable<T>.

**Comment by litenova** [comment]
Would you add more details? like sample code?

**Comment by TorreyGarland** [comment]
at first I tried to execute an EF core query, returning the results using AsAsyncEnumerable().  I verified that the query would return at least one result.  

When the EF query did not work, I tried just "yield return" without the DB call.  Still got a null result.

**Comment by litenova** [comment]
Take the code below as an example:

```c#
    public class CardQueryModel
    {
        public int Id { get; set; }
        
        public string Title { get; set; }
    }
    
    public class StreamCarsQuery : IStreamQuery<CardQueryModel>
    {
        
    }

    public class StreamCarsQueryHandler : IStreamQueryHandler<StreamCarsQuery, CardQueryModel>
    {
        private readonly ApplicationDatabaseContext _dbContext;

        public StreamCarsQueryHandler(ApplicationDatabaseContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async IAsyncEnumerable<CardQueryModel> Handle(StreamCarsQuery message)
        {
            var cars = _dbContext.Cars.AsAsyncEnumerable();

            await foreach (var car in cars)
            {
                yield return new CardQueryModel
                {
                    Id = car.Id,
                    Title = car.Title
                };
            }
        }
    }
```

**Comment by TorreyGarland** [comment]
I tried code very similar to this.  Still returning null.

Exceptions are that the Handle method in the IStreamQueryHandler has a cancellation token in the current version.
